### PR TITLE
dropdown-mixin

### PR DESCRIPTION
**Pull request by nazartokar**

### CODE REVIEW

**Review by jarrodek — CHANGES_REQUESTED** [review]
That is the point of this file to put styles definition for the anypoint dropdown and not to move it outside using mixins.
Please, use this file to put any styling for the dropdows here.

**Comment by nazartokar** [comment]
@jarrodek sorry, didn't get you. What do you mean? 

If you propose to add styling directly to this file: we have `api-console-styles.html` and all stylings for mixing are stored there. It's better for us to keep styling in the same place not to miss anything. And it's much easier to update mixin than create another pull request to this repo.

**Comment by jarrodek** [comment]
No, this repository was created to provide anypoint styling for the anypoint components written as a web components. This repository should contain anypoint components specific styling and the console styles should contain styling for the console. So if you have to change any of the anypoint components (checkboxes, inputs, dropdowns etc) you should do it here, and not in console's styling. It's not scalable because another team would have to do the same thing instead just using this file which is a dependency of anypoint components anyway.
So please, put any styling related to the anyponit components here instead of console's style base.

**Comment by nazartokar** [comment]
@jarrodek I see, updated the repo. Thanks.

**Review by jarrodek — APPROVED** [review]

**Pull request merged**
