### PR TITLE
Dropdown mixin

### PR DESCRIPTION
**Pull request by nazartokar**

### CODE REVIEW

**Review by jarrodek — COMMENTED** [review]
Why do you need those changes? Aren't you suppose to change the new dropdown element itself?

**Comment by nazartokar** [comment]
@jarrodek I expect to have mixins to be able to change everything in Exchange repo easily and not to wait for bower components to update.

As we started updating ARC styles in Exchange `api-console.styles.html`, let's be consistent and continue doing it the same way.

Created another mixin to control borders. Take a look at a screenshot.

screenshot 2017-10-17 13 14 31

**Comment by jarrodek** [comment]
I am thinking about scalability. You are not the only team that is using anypont styling in the console and eventually they will use the same code base for styling. So I don't want it to be too complicated. 
It is complicated if you have anypoint styled element but you still have to style it for anypoint in external file. It doesn't even make sense.

Once again, please, apply the styling here: https://github.com/mulesoft/paper-dropdown-menu
It should not be controlled by the style file.

**Comment by nazartokar** [comment]
@jarrodek ok, I've updated the dropdown using the method you describe. Thanks.

**Pull request closed without merging**
